============================= test session starts ==============================
platform linux -- Python 3.9.16, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/rainer/projects/donkeycar
plugins: cov-4.0.0
collected 136 items / 4 errors

==================================== ERRORS ====================================
______________ ERROR collecting donkeycar/tests/test_actuator.py _______________
donkeycar/tests/test_actuator.py:3: in <module>
    from donkeycar.parts.actuator import PCA9685, PWMSteering, PWMThrottle
donkeycar/parts/actuator.py:19: in <module>
    import RPi.GPIO as GPIO
../../mambaforge/envs/donkey/lib/python3.9/site-packages/RPi/GPIO/__init__.py:1: in <module>
    from Jetson.GPIO import *
../../mambaforge/envs/donkey/lib/python3.9/site-packages/Jetson/GPIO/__init__.py:1: in <module>
    from .gpio import *
../../mambaforge/envs/donkey/lib/python3.9/site-packages/Jetson/GPIO/gpio.py:33: in <module>
    raise RuntimeError("The current user does not have permissions set to access the library functionalites. Please configure permissions or use the root user to run this. It is also possible that {} does not exist. Please check if that file is present.".format(_GPIOCHIP_ROOT))
E   RuntimeError: The current user does not have permissions set to access the library functionalites. Please configure permissions or use the root user to run this. It is also possible that /dev/gpiochip0 does not exist. Please check if that file is present.
------------------------------- Captured stdout --------------------------------
________             ______                   _________              
___  __ \_______________  /___________  __    __  ____/_____ ________
__  / / /  __ \_  __ \_  //_/  _ \_  / / /    _  /    _  __ `/_  ___/
_  /_/ // /_/ /  / / /  ,<  /  __/  /_/ /     / /___  / /_/ /_  /    
/_____/ \____//_/ /_//_/|_| \___/_\__, /      \____/  \__,_/ /_/     
                                 /____/                              

using donkey v5.0.dev1 ...
_____________ ERROR collecting donkeycar/tests/test_tachometer.py ______________
donkeycar/tests/test_tachometer.py:4: in <module>
    from donkeycar.parts.tachometer import Tachometer
donkeycar/parts/tachometer.py:9: in <module>
    from donkeycar.parts.pins import InputPin, PinEdge
donkeycar/parts/pins.py:397: in <module>
    import RPi.GPIO as GPIO
../../mambaforge/envs/donkey/lib/python3.9/site-packages/RPi/GPIO/__init__.py:1: in <module>
    from Jetson.GPIO import *
../../mambaforge/envs/donkey/lib/python3.9/site-packages/Jetson/GPIO/__init__.py:1: in <module>
    from .gpio import *
../../mambaforge/envs/donkey/lib/python3.9/site-packages/Jetson/GPIO/gpio.py:33: in <module>
    raise RuntimeError("The current user does not have permissions set to access the library functionalites. Please configure permissions or use the root user to run this. It is also possible that {} does not exist. Please check if that file is present.".format(_GPIOCHIP_ROOT))
E   RuntimeError: The current user does not have permissions set to access the library functionalites. Please configure permissions or use the root user to run this. It is also possible that /dev/gpiochip0 does not exist. Please check if that file is present.
________________ ERROR collecting donkeycar/tests/test_torch.py ________________
ImportError while importing test module '/home/rainer/projects/donkeycar/donkeycar/tests/test_torch.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/envs/donkey/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
donkeycar/tests/test_torch.py:7: in <module>
    import torch
../../mambaforge/envs/donkey/lib/python3.9/site-packages/torch/__init__.py:218: in <module>
    from torch._C import *  # noqa: F403
E   ImportError: /usr/lib/aarch64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/rainer/mambaforge/envs/donkey/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
________________ ERROR collecting donkeycar/tests/test_train.py ________________
ImportError while importing test module '/home/rainer/projects/donkeycar/donkeycar/tests/test_train.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/envs/donkey/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
donkeycar/tests/test_train.py:13: in <module>
    from donkeycar.pipeline.training import train, BatchSequence
donkeycar/pipeline/training.py:13: in <module>
    from donkeycar.pipeline.database import PilotDatabase
donkeycar/pipeline/database.py:8: in <module>
    import pandas as pd
../../mambaforge/envs/donkey/lib/python3.9/site-packages/pandas/__init__.py:48: in <module>
    from pandas.core.api import (
../../mambaforge/envs/donkey/lib/python3.9/site-packages/pandas/core/api.py:47: in <module>
    from pandas.core.groupby import (
../../mambaforge/envs/donkey/lib/python3.9/site-packages/pandas/core/groupby/__init__.py:1: in <module>
    from pandas.core.groupby.generic import (
../../mambaforge/envs/donkey/lib/python3.9/site-packages/pandas/core/groupby/generic.py:76: in <module>
    from pandas.core.frame import DataFrame
../../mambaforge/envs/donkey/lib/python3.9/site-packages/pandas/core/frame.py:172: in <module>
    from pandas.core.generic import NDFrame
../../mambaforge/envs/donkey/lib/python3.9/site-packages/pandas/core/generic.py:169: in <module>
    from pandas.core.window import (
../../mambaforge/envs/donkey/lib/python3.9/site-packages/pandas/core/window/__init__.py:1: in <module>
    from pandas.core.window.ewm import (
../../mambaforge/envs/donkey/lib/python3.9/site-packages/pandas/core/window/ewm.py:15: in <module>
    import pandas._libs.window.aggregations as window_aggregations
E   ImportError: /usr/lib/aarch64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/rainer/mambaforge/envs/donkey/lib/python3.9/site-packages/pandas/_libs/window/aggregations.cpython-39-aarch64-linux-gnu.so)
=============================== warnings summary ===============================
../../mambaforge/envs/donkey/lib/python3.9/site-packages/pkg_resources/__init__.py:121
  /home/rainer/mambaforge/envs/donkey/lib/python3.9/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
    warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)

../../mambaforge/envs/donkey/lib/python3.9/site-packages/pkg_resources/__init__.py:2870
../../mambaforge/envs/donkey/lib/python3.9/site-packages/pkg_resources/__init__.py:2870
  /home/rainer/mambaforge/envs/donkey/lib/python3.9/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

../../mambaforge/envs/donkey/lib/python3.9/site-packages/pkg_resources/__init__.py:2870
  /home/rainer/mambaforge/envs/donkey/lib/python3.9/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

../../mambaforge/envs/donkey/lib/python3.9/site-packages/flatbuffers/compat.py:19
  /home/rainer/mambaforge/envs/donkey/lib/python3.9/site-packages/flatbuffers/compat.py:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
ERROR donkeycar/tests/test_actuator.py - RuntimeError: The current user does ...
ERROR donkeycar/tests/test_tachometer.py - RuntimeError: The current user doe...
ERROR donkeycar/tests/test_torch.py
ERROR donkeycar/tests/test_train.py
!!!!!!!!!!!!!!!!!!! Interrupted: 4 errors during collection !!!!!!!!!!!!!!!!!!!!
======================== 5 warnings, 4 errors in 18.59s ========================
